apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker 
  name: selinux-policy-patch
spec:
  osImageURL: quay.io/midu/selinux-policy:4.12.2