apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker 
  name: runc-patch
spec:
  osImageURL: quay.io/midu/runc-patch:latest